"""game logs

Revision ID: bd3ee91993be
Revises: fdd3d2397edf
Create Date: 2023-09-21 11:44:00.869234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3ee91993be'
down_revision = 'fdd3d2397edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_log_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_log_timestamp'))

    op.drop_table('game_log')
    # ### end Alembic commands ###
